apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: modsecurity-michaeldelamorena-com
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: modsecurity-michaeldelamorena-com
